### ISSUE TITLE
Optionally exclude logs and/or result browsers when downloading test results in non-interactive mode

### ISSUE THREAD

**Issue by h-arlt** [Xceptance/XLT#129]
When running XLT mastercontroller in non-interactive mode, download of test results will always include logs and result browsers. This might be fine in most cases but sometimes log files and even result browsers may not be needed and/or users simply want to improve download speed by restricting the amount of test results.

For this reasons, XLT mastercontroller should offer an appropriate command line option (or multiple ones) that can be used to restrict the download to certain data types and is effective in non-interactive mode only, e.g. `noLogs` and `noResultBrowsers`. Please notice that `noResultBrowsers` also implies `noLogs`.

**Comment by rschwietzke** [comment]
I suggest to avoid including something indirectly in another option. So noResultBrowsers must not exclude logs, because the name does not imply that. The command line does not have to show the same logic as the UI does. Once implemented we can never change that again easily.

The `noDownload` option already says download nothing. I suggest to make it clearer what the options do, because `noLogs` does not indicate anything in regards to a download for instance. Suggestion: `noResultBrowserDownload` and `noLogsDownload` which fits `noDownload` but they are all not really nicely named options.

Please don't forget that there is a `commands` option that needs different options too.

**Comment by h-arlt** [comment]
Thanks for your feedback @rschwietzke .

Then let's start with a single new option named `download` that takes a comma-separated list of data types as argument. The argument is not optional. Possible values are `logs`, `measurements` and `resultbrowsers`.
In case the option is not given, then all data types will be downloaded. This is equivalent to specifying all data types as option value. 
The options `download` and `noDownload` are mutually exclusive. XLT mastercontroller will exit with an error in case both were given.
