### ISSUE TITLE
Condense Result Browser Files

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#232]
To lower the requirements for disk space and transfer, we should simplify the result browser slightly:

* replace all images with an SVG that are inline, forget the spinner gif and make it a static, remove the images dir
* move both CSS files into the HTML and remove the CSS dir
* condense all JS files (except data.js) into one, validate if the really need Jquery and/or all modules of it, update Jquery at the same time to latest for security reasons
* check if we really need moments.js or if anything lighter is doable
* Deploy condensed version of resultbrowser.js

**Comment by h-arlt** [comment]
Instead of putting efforts into minimizing the result browser, we should consider to dump the data.js/data.har files only and parametrize the result browser to use a specific dump dir and/or provide a CLI tool to "export" the legacy result browser.

This would reduce total size of load test results to fraction of what would be possible with this minimize approach.

**Comment by h-arlt** [comment]
Focused on inlining the required resources first.

Optimizations  (drop moment.js, replace jquery w/ native browser API, use SVG images and so on) tracked as separate tasks
