### ISSUE TITLE
Make the report more speaking on subpages

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/XLT#311]
## General
When XLT reports are created via the XTC SaaS platform (Xceptance Test Center), it will include the following properties with the prefix `com.xceptance.xtc` 

* organization
* project
* loadtest.run.id
* loadtest.result.id
* loadtest.report.id

If these are set, enhance the reports to include some information. See below. 

## Visibility

A first idea is to keep the current read header and add additional information under the "Performance Test Report" Headline, such as `Organization: acme Project: acme2023 Loadtest: #75 Result: #1 Report: #1`. 

When one starts to scroll, the header becomes sticky (together with the menu we already have) and shrinks down to just the height of the above text. The "Performance Test Report" headline is gone at this moment. The logo is also resized to something smaller. When you arrive at the top again, the header returns to normal.

The "Created with Xceptance LoadTest 6.2.3" is moved into the footer as extra line under the copyright.

If the information of XTC is not included, such as this is an independent XLT run, just keep the "Created with Xceptance LoadTest 6.2.3" but still make the header sticky and make it shrink when scrolling.

**Comment by js-xc** [comment]
Now expecting the following properties:

* `com.xceptance.xtc.organization`
* `com.xceptance.xtc.project`
* `com.xceptance.xtc.loadtest.run.id`
* `com.xceptance.xtc.loadtest.result.id`
* `com.xceptance.xtc.loadtest.report.id`

If these are not found, the previous line (_Created with Xceptance LoadTest ?.?.?_) will be displayed.

What about the _Comment_ section on the overview page? This probably contains the same information in case of XTC-generated reports - are we omitting this section then because the info is already in the header?

**Comment by rschwietzke** [comment]
We don't omit that section. The header is a meant to aid the user when scrolling or being on subpages. The comment section also contains verbal comments, the header cannot display that easily, and we have not planned to include that as an extra property at the moment.
