### ISSUE TITLE
Comparison Report: Add custom values page

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT#489]
Add a Custom Values page to the comparison report that compares the custom value measurements of the two runs.

**Comment by js-xc** [comment]
Open: since we can't know on a semantic level what those custom values are, it does not make so much sense to mark changes as good=green, bad=red - we don't have an idea if an increase is good or bad. Also, in the example that is often used in load tests, the long runners are counted per scenario and usually there are different scenarios with a few long runners each on different load tests, but marking these in light gray as added/removed also does not quite hit it semantically...

**Comment by jowerner** [comment]
> Open: since we can't know on a semantic level what those custom values are, it does not make so much sense to mark changes as good=green, bad=red - we don't have an idea if an increase is good or bad. 

True. Maybe we can use a yellowish color instead of read/green. I thought about using the absolute difference between the old and new value to determine the shade to apply, but then again, we don't know what is a small difference and what is a significant difference. So it's either just highlighting the cell with yellow if the values are different or not coloring the cell at all.

**Comment by jowerner** [comment]
> Also, in the example that is often used in load tests, the long runners are counted per scenario and usually there are different scenarios with a few long runners each on different load tests, but marking these in light gray as added/removed also does not quite hit it semantically...

I believe it is okay to mark custom value cells as "(added)" or "(removed)" if values appear in only one of the two reports. In general, comparing reports only makes sense for very similar runs, i.e. same scenario set, same load profile. So we should be fine here.
